const data = [
    {
        id: 1,
        title: "Car Toys",
        img: "1.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 2,
        title: "Carols Daughter",
        img: "2.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 3,
        title: "Amazon",
        img: "3.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 4,
        title: "Baseball Savings",
        img: "4.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 5,
        title: "Ashford",
        img: "5.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 6,
        title: "Callaway Golf",
        img: "6.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 7,
        title: "Car Toys",
        img: "1.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 8,
        title: "Carols Daughter",
        img: "2.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 9,
        title: "Amazon",
        img: "3.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 10,
        title: "Baseball Savings",
        img: "4.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 11,
        title: "Ashford",
        img: "5.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
        id: 12,
        title: "Callaway Golf",
        img: "6.png",
		location: "gulshan, dhaka",
		establish: "2010",
		size: "5 - 10",
		email: "example@email.com",
		url: "apple.com",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    }
];

export default data;